Controllers/POSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pharmacy.Models;
using Pharmacy.ViewModel;
using Pharmacy.Repositories;

namespace Pharmacy.Controllers
{
    public class POSController : Controller
    {
        private PharmacyDatabaseEntities objPharmacyDatabaseEntities;
        public POSController()
        {
            objPharmacyDatabaseEntities = new PharmacyDatabaseEntities();
        }
        public ActionResult Index()
        {

            CustomerRepository objCustomerRepository = new CustomerRepository();
            ItemRepository objItemRepository = new ItemRepository();
            PaymentTypeRepository objPaymentTypeRepository = new PaymentTypeRepository();


            var objMultipleModels = new Tuple<IEnumerable<SelectListItem>, IEnumerable<SelectListItem>, IEnumerable<SelectListItem>>
                (objCustomerRepository.GetAllCustomers(), objItemRepository.GetAllItems(), objPaymentTypeRepository.GetAllPaymentType());


            return View(objMultipleModels);
        }
        [HttpGet]
        public JsonResult getItemUnitPrice(int ItemID)
        {
            decimal UnitPrice = Convert.ToDecimal(objPharmacyDatabaseEntities.tblMedications.Single(model => model.ItemID == ItemID).Price);
            return Json(UnitPrice, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Index(SalesViewModel objSalesViewModel)
        {
            SalesRepository objSalesRepository = new SalesRepository();
            objSalesRepository.AddSales(objSalesViewModel);

            return Json("Your Sale has been Successfully Created!", JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ballantine's Pharmacy Management System</title>
    <link rel="stylesheet" href="~/Content/Style.css"/>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (Session["Role"].ToString() == "Pharmacist")
    {

        <div class="nav">
            <ul>
                <content>
                    <img src="~/Content/Untitled.jpg" style="
        float: left;
        width: 120px;
        height: 100px;
        margin-top: 10px;
        margin-left: 10px;
        margin-bottom: 10px;" />
                </content>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Users", "Index", "Users")</li>
                <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                <li>@Html.ActionLink("Medications", "Index", "Medications")</li>
                <li>@Html.ActionLink("Chronic Medication", "Index", "ChronicMedications")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("Patients", "Index", "Patients")</li>
                <li>@Html.ActionLink("Create Sale", "Index", "POS")</li>
                <li>@Html.ActionLink("Sales History", "Index", "SalesDetails")</li>
                <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            </ul>

            <ul class="nav navbar-right" style="font:black;">
            </ul>

        </div>



    }
    @if (Session["Role"].ToString() == "Assisstant")
    {
        <div class="nav">
            <ul>
                <content>
                    <img src="~/Content/Untitled.jpg" style="
        float: left;
        width: 120px;
        height: 100px;
        margin-top: 10px;
        margin-left: 10px;
        margin-bottom: 10px;" />
                </content>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Medications", "Index", "Medications")</li>
                <li>@Html.ActionLink("Chronic Medication", "Index", "ChronicMedications")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("Patients", "Index", "Patients")</li>
                <li>@Html.ActionLink("Create Sale", "Index", "POS")</li>
                <li>@Html.ActionLink("Sales History", "Index", "SalesDetails")</li>
                <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
            </ul>

            <ul class="nav navbar-right" style="font:black;">
            </ul>
        </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ballantine's Pharmacy Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>